package Shield;

public enum ZoneFlags {
    ALLOW_FLOW,
    ALLOW_MOB_SPAWN,
    ALLOW_INTERACT,
    ALLOW_PVP,
    ALLOW_BREAK,
    ALLOW_PLACE,
    ALLOW_TELEPORT_IN,
    ALLOW_TELEPORT_OUT,
    ALLOW_FLY,
    ALLOW_PISTONS;
}

